import type { Metadata } from "next";
import RecoilRootWrapper from "@/components/recoilWapper";
import Layout from "../components/layout/layout";
import { Jua } from "next/font/google";
import Script from "next/script";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
// @를 떼주자
import "./globals.css";
import theme from "./theme";

import CssBaseline from "@mui/material/CssBaseline";
import { ThemeProvider } from "@mui/material/styles";
//
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

declare global {
  interface Window {
    kakao: any;
  }
}
const queryClient = new QueryClient();
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="m-0 h-screen overflow-auto">
        {" "}
        {/* 전체 페이지 스크롤 허용 */}
        <div className="h-full bg-[url('/img/background.png')] bg-cover bg-center overflow-hidden">
          {" "}
          {/* 배경 div */}
          <ThemeProvider theme={theme}>
            <RecoilRootWrapper>
              <Layout>
                {/* <Script
                type="text/javascript"
                src={`https://oapi.map.naver.com/openapi/v3/maps.js?ncpClientId=${process.env.NEXT_PUBLIC_NAVER_CLIENT_ID}&callback=CALLBACK_FUNCTION`}
              /> */}
                {/* <Script
                // type="text/javascript"

                src={`https://dapi.kakao.com/v2/maps/sdk.js?appkey=${process.env.NEXT_PUBLIC_JS_KAKAO_CLIENT_KEY}&libraries=services&autoload=false`}
              /> */}
                <main>{children}</main>
              </Layout>
            </RecoilRootWrapper>
          </ThemeProvider>
        </div>
      </body>
    </html>
  );
}
